name = "Casper-Full"
license = "MIT"
licenselink = ""
description = "A More Robust Casper theme from Ghost Foundation"
homepage = ""
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "Sam Jones"
  homepage = ""

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
